#!bin/bash
matlakjds;fakdjf;ldkfj;ldkfj;ladkfj;lasdkfj;laskdfj;lasdkfj;laskfj;alskfj;laskdfj;laskfj;laskfj;dkfj;laskfj;alskfj;laskfj;laskfj;laskjf;laskjf;laskjf;laksdfj;laskfj;aldskfj;ladksfj;laksfj;laksfj;laskfj;lkdajfi
